### ISSUE TITLE
litcoffee support

### ISSUE THREAD

**Issue by mattlima** [caseywebdev/CoffeeScript.mode#7]
Hey there,
thanks for this, I use it all the time. I started working with .litcoffee files and I created a [version of your code](https://github.com/mattlima/litcoffee.mode) for that format. I'd like to make sure you're credited appropriately (as you've done with Sean Durham). If you'd like the license/docs changed on my repo at all, please let me know.

**Comment by caseywebdev** [comment]
Looks great!

**Comment by mattlima** [comment]
Thanks!
